defmodule Vutuv.VideosTest do
  @moduledoc """
  Video on posts, the context half (issues #1907, #1908, #1910): the upload's
  gates, the pipeline's steps and their stamps, the AI check over the frames,
  and the post that waits for its clip.

  The clips are real (tiny, generated by ffmpeg's test source) and the job
  runs the real ffmpeg, so what is asserted is what a member gets: files on
  disk, stamps on the row, a post that appears when the last of the two
  gates opens.
  """

  use Vutuv.DataCase

  import Ecto.Query

  alias Vutuv.Moderation.ImageScans
  alias Vutuv.Posts
  alias Vutuv.Posts.PendingVideoPost
  alias Vutuv.Posts.PostVideo
  alias Vutuv.PostVideoStore
  alias Vutuv.Repo
  alias Vutuv.VideoFixtures
  alias Vutuv.Videos
  alias Vutuv.Videos.Job

  setup do
    tmp = Path.join(System.tmp_dir!(), "vutuv_videos_#{System.unique_integer([:positive])}")
    File.mkdir_p!(tmp)
    prev = Application.get_env(:vutuv, :uploads_dir_prefix)
    Application.put_env(:vutuv, :uploads_dir_prefix, tmp)

    on_exit(fn ->
      File.rm_rf(tmp)

      if prev,
        do: Application.put_env(:vutuv, :uploads_dir_prefix, prev),
        else: Application.delete_env(:vutuv, :uploads_dir_prefix)
    end)

    %{user: insert_activated_user(), tmp: tmp}
  end

  defp upload!(user, path \\ VideoFixtures.mp4_path()) do
    {:ok, video} = Videos.create_pending_video(user, path, Path.basename(path))
    video
  end

  defp reload(video), do: Videos.get_video(video.id)

  describe "create_pending_video/3" do
    test "keeps the original, probes it and queues the pipeline", %{user: user} do
      video = upload!(user)

      assert video.stage == "queued"
      assert video.duration_ms in 2_900..3_100
      assert {video.width, video.height} == {320, 180}
      assert video.content_type == "video/mp4"
      assert video.size_bytes > 0
      assert PostVideoStore.original_path(video.token)
      assert Videos.pending_video(user, video.id).id == video.id
    end

    test "refuses a file over the size cap before reading it", %{user: user} do
      prev = Application.get_env(:vutuv, :post_videos)
      Application.put_env(:vutuv, :post_videos, Keyword.put(prev, :max_filesize, 10))
      on_exit(fn -> Application.put_env(:vutuv, :post_videos, prev) end)

      assert {:error, :too_large} =
               Videos.create_pending_video(user, VideoFixtures.mp4_path(), "tiny.mp4")
    end

    test "refuses a clip over the length cap after probing it", %{user: user} do
      prev = Application.get_env(:vutuv, :post_videos)
      Application.put_env(:vutuv, :post_videos, Keyword.put(prev, :max_duration_seconds, 2))
      on_exit(fn -> Application.put_env(:vutuv, :post_videos, prev) end)

      assert {:error, :too_long} =
               Videos.create_pending_video(user, VideoFixtures.mp4_path(), "tiny.mp4")

      assert {:ok, _} =
               Videos.create_pending_video(
                 user,
                 VideoFixtures.silent_mp4_path(),
                 "silent.mp4"
               )
    end

    test "refuses what is not a video", %{user: user, tmp: tmp} do
      fake = Path.join(tmp, "not-a-video.mp4")
      File.write!(fake, "hello")
      assert {:error, :invalid_file} = Videos.create_pending_video(user, fake, "not-a-video.mp4")

      assert {:error, :invalid_file} =
               Videos.create_pending_video(user, VideoFixtures.mp4_path(), "tiny.txt")
    end

    test "takes a WebM too", %{user: user} do
      video = upload!(user, VideoFixtures.webm_path())
      assert video.content_type == "video/webm"
    end
  end

  describe "the pipeline" do
    test "pulls the frames, writes every rendition and the cover, and stamps each step",
         %{user: user} do
      video = upload!(user)
      Videos.subscribe(user.id)

      assert :ok = Job.run(video.id)
      video = reload(video)

      assert video.frames_extracted_at
      assert video.h264_ready_at
      assert video.av1_ready_at
      assert video.lite_ready_at
      assert video.cover_written_at
      assert video.stage == "ready"
      assert video.progress == 100
      assert video.worked_at == nil

      # A three-second clip gets its opening frame, plus the representative
      # opening second when it differs.
      assert video.frames != []
      assert Enum.all?(video.frames, &(&1.moderation == "approved"))
      assert video.cover_frame_id in Enum.map(video.frames, & &1.id)

      assert PostVideoStore.rendition_path(video.token, "h264")
      assert PostVideoStore.rendition_path(video.token, "lite-h264")
      assert PostVideoStore.cover_path(video.token, :full)
      assert PostVideoStore.cover_path(video.token, :lite)

      for frame <- video.frames do
        assert File.exists?(PostVideoStore.frame_path(video.token, frame.position))
      end

      # The author's tile heard about it along the way, and the final state.
      assert_received {:post_video, %{stage: "frames"}}
      assert_received {:post_video, %{stage: "transcoding"}}
      assert_received {:post_video, %{stage: "ready", progress: 100}}
    end

    test "a clip with no audio track converts too", %{user: user} do
      video = upload!(user, VideoFixtures.silent_mp4_path())
      assert :ok = Job.run(video.id)
      assert reload(video).stage == "ready"
    end

    test "a run killed mid-way is resumed from the step it lost", %{user: user} do
      video = upload!(user)

      # First run: the frames step, then the process dies before any file is
      # finished (the H.264 encode of a deploy's killed slot). Unlinked, so the
      # kill takes the job and not the test.
      pid = spawn(fn -> Job.run(video.id) end)

      wait_until(fn -> reload(video).stage == "transcoding" end)
      Process.exit(pid, :kill)
      wait_until(fn -> not Process.alive?(pid) end)
      # The temp file the encode was writing may still be there.
      assert reload(video).h264_ready_at == nil
      assert reload(video).frames_extracted_at

      # The claim is stale in the sweeper's eyes only after the window; here
      # the row is handed back the way a dead heartbeat would be.
      from(v in PostVideo, where: v.id == ^video.id)
      |> Repo.update_all(
        set: [worked_at: DateTime.add(DateTime.utc_now(:second), -3600, :second)]
      )

      assert [claimed] = Videos.claim_due(2)
      assert claimed.id == video.id
      assert :ok = Job.run(video.id)

      resumed = reload(video)
      assert resumed.stage == "ready"
      # The frames were not pulled twice: same rows, same stamp.
      assert resumed.frames_extracted_at == reload(video).frames_extracted_at
      assert PostVideoStore.rendition_path(video.token, "h264")

      # And the temp file the killed encode was writing is gone.
      dir = Path.dirname(PostVideoStore.rendition_path(video.token, "h264"))
      assert Path.wildcard(Path.join(dir, ".*.mp4"), match_dot: true) == []
    end

    test "claim_due works the clips missing their H.264 file before the enhancements",
         %{user: user} do
      older = upload!(user)
      newer = upload!(user)

      # The older one already has its main file, the newer one nothing yet.
      from(v in PostVideo, where: v.id == ^older.id)
      |> Repo.update_all(
        set: [
          frames_extracted_at: DateTime.utc_now(:second),
          h264_ready_at: DateTime.utc_now(:second)
        ]
      )

      assert [first, second] = Videos.claim_due(2)
      assert first.id == newer.id
      assert second.id == older.id

      # Both are claimed now: nobody else gets them until the heartbeat is stale.
      assert [] = Videos.claim_due(2)
    end

    test "a job that cannot read the clip fails it with a reason", %{user: user} do
      video = upload!(user)
      File.rm!(PostVideoStore.original_path(video.token))

      assert :ok = Job.run(video.id)
      failed = reload(video)
      assert failed.stage == "failed"
      assert failed.error =~ "missing_original"
      assert PostVideo.refused?(failed)
    end
  end

  describe "the AI check over the frames" do
    setup do
      prev = Application.get_env(:vutuv, :moderate_images)
      Application.put_env(:vutuv, :moderate_images, true)
      on_exit(fn -> Application.put_env(:vutuv, :moderate_images, prev) end)
      :ok
    end

    test "every frame is scanned; the last one to pass releases the clip", %{user: user} do
      video = upload!(user)
      assert :ok = Job.run(video.id)

      checking = reload(video)
      assert checking.h264_ready_at
      assert checking.moderation == "pending"
      assert checking.stage == "checking"
      assert Enum.all?(checking.frames, &(&1.moderation == "pending"))

      scans = ImageScans.list_due()
      assert length(scans) == length(checking.frames)
      assert Enum.all?(scans, &(&1.kind == "post_video_frame"))

      ImageScans.deliver_due(judge: fn _path -> {:ok, %{safe?: true}} end)

      released = reload(video)
      assert released.moderation == "approved"
      assert released.stage == "ready"
      assert Enum.all?(released.frames, &(&1.moderation == "approved"))
    end

    test "one refused frame refuses the clip at that second, and every file goes",
         %{user: user} do
      video = upload!(user)
      Videos.subscribe(user.id)
      Vutuv.Activity.subscribe(user.id)
      assert :ok = Job.run(video.id)
      assert PostVideoStore.rendition_path(video.token, "h264")

      ImageScans.deliver_due(
        judge: fn _path -> {:ok, %{safe?: false, category: "nudity", reason: "test"}} end
      )

      refused = reload(video)
      assert refused.moderation == "rejected"
      assert refused.stage == "rejected"
      assert is_integer(refused.rejected_second)
      refute PostVideoStore.rendition_path(video.token, "h264")
      refute PostVideoStore.original_path(video.token)
      assert_received {:post_video, %{stage: "rejected"}}

      # The owner is told, like for a photo.
      assert_received {:new_notification,
                       %{kind: "image_rejected", image_kind: "post_video_frame"}}
    end

    test "a frame whose file is gone cancels its scan rather than judging nothing",
         %{user: user} do
      video = upload!(user)
      assert :ok = Job.run(video.id)
      PostVideoStore.clear_frames(video.token)

      ImageScans.deliver_due(judge: fn _path -> flunk("nothing to judge") end)
      assert reload(video).moderation == "pending"
    end

    test "repair_drift re-queues a frame whose scan was never enqueued", %{user: user} do
      video = upload!(user)
      assert :ok = Job.run(video.id)
      Repo.delete_all(Vutuv.Moderation.ImageScan)

      assert ImageScans.repair_drift() == length(reload(video).frames)
    end
  end

  describe "the post that waits for its clip" do
    test "is published the moment the clip is ready, through the composer's own create path",
         %{user: user} do
      video = upload!(user)
      Videos.subscribe(user.id)

      attrs = %{
        body: "Watch this",
        tags: "talks",
        license: "all_rights_reserved",
        image_ids: [],
        denials: []
      }

      {:ok, pending} = Videos.create_pending_post(user, video, "post", %{}, attrs)
      assert pending.status == "waiting"
      assert Videos.in_progress_summary(user.id) == %{count: 1, progress: nil}
      assert [%PendingVideoPost{id: id}] = Videos.pending_posts_for(user)
      assert id == pending.id

      assert :ok = Job.run(video.id)

      published = Repo.get!(PendingVideoPost, pending.id)
      assert published.status == "published"
      post = Posts.get_post(published.post_id)
      assert post.body == "Watch this"
      assert post.video.id == video.id
      assert Enum.map(post.tags, & &1.name) == ["talks"]
      assert reload(video).post_id == post.id

      post_id = post.id
      assert_received {:pending_video_post, %{status: "published", post_id: ^post_id}}

      assert Videos.pending_posts_for(user) == []
      assert Videos.in_progress_summary(user.id) == %{count: 0, progress: nil}
    end

    test "a clip that is already ready publishes on the spot", %{user: user} do
      video = upload!(user)
      assert :ok = Job.run(video.id)

      {:ok, pending} = Videos.create_pending_post(user, video, "post", %{}, %{body: "Now"})
      assert Repo.get!(PendingVideoPost, pending.id).status == "published"
    end

    test "a reply waits and then answers its parent", %{user: user} do
      parent = insert(:post, user: insert_activated_user())
      video = upload!(user)

      {:ok, pending} =
        Videos.create_pending_post(user, video, "reply", %{parent: parent}, %{body: "Re"})

      assert :ok = Job.run(video.id)
      published = Repo.get!(PendingVideoPost, pending.id)
      assert published.status == "published"

      assert Repo.get_by!(Vutuv.Posts.PostReply, post_id: published.post_id).parent_post_id ==
               parent.id
    end

    test "a refused clip keeps the text waiting, and the author can post without it",
         %{user: user} do
      video = upload!(user)
      {:ok, pending} = Videos.create_pending_post(user, video, "post", %{}, %{body: "Text stays"})

      Application.put_env(:vutuv, :moderate_images, true)
      on_exit(fn -> Application.put_env(:vutuv, :moderate_images, false) end)
      assert :ok = Job.run(video.id)

      ImageScans.deliver_due(
        judge: fn _path -> {:ok, %{safe?: false, category: "violence", reason: "test"}} end
      )

      assert Repo.get!(PendingVideoPost, pending.id).status == "waiting"

      assert [%PendingVideoPost{video: %PostVideo{stage: "rejected"}}] =
               Videos.pending_posts_for(user)

      pending = Videos.get_pending_post(user, pending.id)
      assert {:ok, post} = Videos.publish_without_video(pending)
      assert post.body == "Text stays"
      assert post.video == nil
      assert Repo.get(PostVideo, video.id) == nil
    end

    test "cancelling drops the text and the clip", %{user: user} do
      video = upload!(user)
      {:ok, pending} = Videos.create_pending_post(user, video, "post", %{}, %{body: "Never mind"})

      assert :ok = Videos.cancel_pending_post(pending)
      assert Repo.get!(PendingVideoPost, pending.id).status == "canceled"
      assert Repo.get(PostVideo, video.id) == nil
      refute PostVideoStore.original_path(video.token)
    end

    test "a post cannot claim a clip that is not ready", %{user: user} do
      video = upload!(user)

      assert {:error, :invalid_video} =
               Posts.create_post(user, %{body: "Too soon", video_id: video.id})

      assert :ok = Job.run(video.id)
      assert {:ok, post} = Posts.create_post(user, %{body: "", video_id: video.id})
      assert post.video.id == video.id

      # And never twice.
      assert {:error, :invalid_video} =
               Posts.create_post(user, %{body: "Again", video_id: video.id})
    end
  end

  describe "housekeeping" do
    test "sweep_pending_videos removes abandoned clips but not those a draft or a pending post names",
         %{user: user} do
      abandoned = upload!(user)
      drafted = upload!(user)
      waiting = upload!(user)
      :ok = Posts.save_draft(user, nil, %{body: "draft", video_id: drafted.id})
      assert Posts.get_draft(user, nil).video_id == drafted.id
      {:ok, _} = Videos.create_pending_post(user, waiting, "post", %{}, %{body: "wait"})

      old = DateTime.add(DateTime.utc_now(:second), -48 * 3600, :second)
      Repo.update_all(from(v in PostVideo), set: [inserted_at: old])

      assert Videos.sweep_pending_videos() == 1
      assert Repo.get(PostVideo, abandoned.id) == nil
      assert Repo.get(PostVideo, drafted.id)
      assert Repo.get(PostVideo, waiting.id)
    end

    test "deleting the post deletes the clip's files", %{user: user} do
      video = upload!(user)
      assert :ok = Job.run(video.id)
      {:ok, post} = Posts.create_post(user, %{body: "Bye", video_id: video.id})

      assert {:ok, _} = Posts.delete_post(post)
      refute PostVideoStore.original_path(video.token)
      refute PostVideoStore.rendition_path(video.token, "h264")
      assert Repo.get(PostVideo, video.id) == nil
    end
  end

  defp wait_until(fun, tries \\ 200) do
    cond do
      fun.() ->
        :ok

      tries == 0 ->
        flunk("condition never held")

      true ->
        Process.sleep(25)
        wait_until(fun, tries - 1)
    end
  end
end
