defmodule Vutuv.Webhooks.Subscription do
  @moduledoc """
  A registered app's webhook subscription: which events to deliver to
  which HTTPS endpoint, signed with `secret` (generated by us, shown to
  the developer once, stored as written because every delivery is signed
  with it). `active` is flipped off after sustained delivery failure —
  see `Vutuv.Webhooks`.
  """

  use VutuvWeb, :model

  alias Vutuv.Webhooks

  schema "webhook_subscriptions" do
    belongs_to(:app, Vutuv.ApiAuth.App)

    field(:url, :string)
    field(:secret, :string)
    field(:events, {:array, :string}, default: [])
    field(:active, :boolean, default: true)
    field(:disabled_reason, :string)
    field(:consecutive_failures, :integer, default: 0)

    timestamps()
  end

  def changeset(subscription, params \\ %{}) do
    subscription
    |> cast(params, [:url, :events])
    |> validate_required([:url])
    |> validate_length(:url, max: 500)
    |> validate_url()
    |> validate_events()
  end

  # https only — localhost http for development, mirroring the OAuth
  # redirect URI rule.
  defp validate_url(changeset) do
    validate_change(changeset, :url, fn :url, url ->
      if Vutuv.ApiAuth.App.valid_redirect_uri?(url) do
        []
      else
        [url: "must be an https:// URL (http://localhost is allowed for development)"]
      end
    end)
  end

  defp validate_events(changeset) do
    changeset = validate_subset(changeset, :events, Webhooks.events())

    case get_field(changeset, :events) do
      [_at_least_one | _] -> changeset
      _empty -> add_error(changeset, :events, "select at least one event")
    end
  end
end
