defmodule Vutuv.VideoFixtures do
  @moduledoc """
  Tiny clips for the video tests (issue #1906), generated by ffmpeg's test
  sources at first use rather than checked in: a binary fixture in the repo
  would be the one kind of member-upload-shaped file the gitignore test
  exists to keep out, and generating one costs a third of a second.

  Every test that touches a clip needs ffmpeg on the machine, as production
  does; the suite says so rather than silently skipping.
  """

  @doc "A 3-second 320×180 H.264 MP4 with a sine tone; the same file every call."
  def mp4_path, do: clip("tiny.mp4", ["-c:v", "libx264", "-pix_fmt", "yuv420p", "-c:a", "aac"])

  @doc "A 2-second clip with no audio track."
  def silent_mp4_path,
    do: clip("silent.mp4", ["-c:v", "libx264", "-pix_fmt", "yuv420p", "-an"], seconds: 2)

  @doc "A 3-second VP9/Opus WebM."
  def webm_path,
    do:
      clip("tiny.webm", ["-c:v", "libvpx-vp9", "-b:v", "150k", "-c:a", "libopus", "-b:a", "32k"])

  @doc "The bytes of the standard clip, for `file_input/4`."
  def mp4_binary, do: File.read!(mp4_path())

  defp clip(name, codec_args, opts \\ []) do
    seconds = Keyword.get(opts, :seconds, 3)
    dir = Path.join(System.tmp_dir!(), "vutuv_video_fixtures")
    File.mkdir_p!(dir)
    path = Path.join(dir, name)

    unless File.exists?(path) do
      audio? = "-an" not in codec_args

      inputs =
        ["-f", "lavfi", "-i", "testsrc2=size=320x180:rate=15"] ++
          if(audio?, do: ["-f", "lavfi", "-i", "sine=frequency=440:sample_rate=44100"], else: [])

      args =
        ["-hide_banner", "-loglevel", "error", "-y"] ++
          inputs ++ ["-t", "#{seconds}"] ++ codec_args ++ ["-movflags", "+faststart", path]

      case System.cmd(ffmpeg(), args, stderr_to_stdout: true) do
        {_, 0} -> :ok
        {out, status} -> raise "ffmpeg could not write the #{name} fixture (#{status}): #{out}"
      end
    end

    path
  end

  defp ffmpeg do
    System.find_executable("ffmpeg") ||
      raise "ffmpeg is not installed; the video tests need it (as production does)"
  end
end
