defmodule Vutuv.Repo.Migrations.CreateWebhooks do
  use Ecto.Migration

  def change do
    # Webhooks (Vutuv.Webhooks): per-app subscriptions and the DB-backed
    # delivery queue. Purely additive, N-1 safe.

    # What an app wants to hear about and where. The signing secret is
    # stored as written (we must sign every delivery with it); it is
    # generated by us, shown to the developer once in the UI.
    create table(:webhook_subscriptions) do
      add(:app_id, references(:oauth_apps, on_delete: :delete_all), null: false)
      add(:url, :string, null: false)
      add(:secret, :string, null: false)
      add(:events, {:array, :string}, null: false, default: [])
      add(:active, :boolean, null: false, default: true)
      add(:disabled_reason, :string)
      add(:consecutive_failures, :integer, null: false, default: 0)

      timestamps()
    end

    create(index(:webhook_subscriptions, [:app_id]))

    # One row per (event, subscription): the queue. `next_attempt_at` drives
    # the poller; exponential backoff bumps it on failure, `delivered_at`
    # closes the row.
    create table(:webhook_deliveries) do
      add(:subscription_id, references(:webhook_subscriptions, on_delete: :delete_all),
        null: false
      )

      add(:event, :string, null: false)
      add(:payload, :map, null: false, default: %{})
      add(:attempts, :integer, null: false, default: 0)
      add(:next_attempt_at, :utc_datetime, null: false)
      add(:delivered_at, :utc_datetime)
      add(:last_status, :integer)
      add(:last_error, :string)

      timestamps()
    end

    create(
      index(:webhook_deliveries, [:next_attempt_at], where: "delivered_at IS NULL")
    )

    create(index(:webhook_deliveries, [:subscription_id]))
  end
end
