# Refreshes `priv/isbn_ranges.txt`, the table `Vutuv.Isbn.format/1` hyphenates
# stored ISBNs with.
#
# Usage:  mix run scripts/update_isbn_ranges.exs
#
# It downloads the International ISBN Agency's RangeMessage (the authoritative
# list of registration group and registrant ranges) and boils its ~1.5 MB of
# XML down to one `prefix low high length` line per rule. Run it when a review
# shows an un-hyphenated ISBN that should split — a stale table only means a
# newly assigned publisher range is not known yet, in which case the card falls
# back to the bare digits, so refreshing is housekeeping, never urgent.

url = "https://www.isbn-international.org/export_rangemessage.xml"
target = "priv/isbn_ranges.txt"

IO.puts("fetching #{url} …")
xml = Req.get!(url, receive_timeout: 60_000).body

date =
  case Regex.run(~r{<MessageDate>(.+?)</MessageDate>}, xml) do
    [_, date] -> date
    nil -> "unknown"
  end

# Both blocks have the same shape (<Prefix> + <Rule>s of <Range>/<Length>);
# only the wrapper element differs, so one scan covers EAN prefixes ("978")
# and registration groups ("978-3") alike.
rules =
  ~r{<(?:EAN\.UCC|Group)>\s*<Prefix>(.+?)</Prefix>.*?<Rules>(.*?)</Rules>}s
  |> Regex.scan(xml)
  |> Enum.flat_map(fn [_, prefix, rules] ->
    ~r{<Range>(\d+)-(\d+)</Range>\s*<Length>(\d+)</Length>}
    |> Regex.scan(rules)
    |> Enum.map(fn [_, low, high, length] -> "#{prefix} #{low} #{high} #{length}" end)
  end)

header = """
# ISBN hyphenation ranges — generated by scripts/update_isbn_ranges.exs, do not
# hand-edit. Source: International ISBN Agency RangeMessage (#{url}),
# message date: #{date}.
#
# One rule per line: <prefix> <low> <high> <length>. The prefix is either an
# EAN.UCC prefix ("978") whose rules give the registration group length, or a
# group ("978-3") whose rules give the registrant length. Low/high bound the
# seven digits following the prefix; a length of 0 marks an unassigned range.
"""

File.write!(target, [header, Enum.join(rules, "\n"), "\n"])
IO.puts("wrote #{length(rules)} rules to #{target}")
